targets:
  $default:
    builders:
      drift_dev:
        options:
          databases:
            tabiya: lib/data/db/database.dart
          schema_dir: drift_schemas/
          test_dir: test/drift/
          store_date_time_values_as_text: false
